apiVersion: v2
name: vault
description: HashiCorp Vault deployment
type: application
version: 1.0.0
dependencies:
  - name: vault
    version: 0.28.0
    repository: https://helm.releases.hashicorp.com
