apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/REPLACE_WITH_YOUR_GITHUB_USERNAME/labapiserver.git
    targetRevision: main
    path: iac/apps/fluent-bit
  destination:
    server: https://kubernetes.default.svc
    namespace: fluent-bit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
