apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: labapiserver
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: labapiserver=ghcr.io/mvarshney/labapiserver
    argocd-image-updater.argoproj.io/labapiserver.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
spec:
  project: default
  source:
    repoURL: https://github.com/mvarshney/labapiserver.git
    targetRevision: main
    path: iac/apps/labapiserver
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: labapiserver
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
